const types = {
  CREATE_DECK_REQUEST: 'CREATE_DECK_REQUEST',
  CREATE_DECK_SUCCESS: 'CREATE_DECK_SUCCESS',
  CREATE_DECK_FAILURE: 'CREATE_DECK_FAILURE',
  SORT_DECK_REQUEST: 'SORT_DECK_REQUEST',
  SORT_DECK_SUCCESS: 'SORT_DECK_SUCCESS',
  SORT_DECK_FAILURE: 'SORT_DECK_FAILURE',
};

export default types;
